version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform
      - curl -O https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip
      - unzip terraform_0.14.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Checking AWS login....
      - aws --version
      - aws sts get-caller-identity
  build:
    commands:
      - echo Initializing Terraform
      - terraform init
      - echo Planning Deployment
      - terraform plan -out=tfplan
      - echo Applying Deployment
      - terraform apply -auto-approve tfplan
  post_build:
    commands:
      - echo Waiting for 5 minutes before destroying the deployment
      - sleep 300
      - echo Destroying Deployment
      - terraform destroy -auto-approve
artifacts:
  files:
    - '**/*'
